# Generated by Django 4.2.3 on 2023-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='titulo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
