# Generated by Django 4.2.3 on 2023-07-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
