# Generated by Django 4.2.3 on 2023-07-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_imagenproducto_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productos.productos'),
        ),
    ]
