# Generated by Django 4.2.3 on 2023-07-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_productos_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='video',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
