# Generated by Django 4.2.3 on 2023-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_productos_envio_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
