# Generated by Django 4.2.3 on 2023-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
